import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "athletic/components/header";

const interDefault = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO: set global inter font
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sk">
      <body
        className={`${interDefault.variable} antialiased global-px`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
